# Generated by Django 6.0.1 on 2026-06-01 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('refund', 'Refund Policy')], max_length=32)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown. Rendered with react-markdown on the frontend.')),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['slug', '-version'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='uniq_policy_slug_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('slug',), name='uniq_active_policy_per_slug')],
            },
        ),
    ]
