# Generated by Django 6.0.1 on 2026-06-29 12:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='e.g., 5.00 for 5%', max_digits=5)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly base salary in BDT (relevant for Level 3)', max_digits=10)),
            ],
            options={
                'ordering': ['commission_percentage'],
            },
        ),
        migrations.CreateModel(
            name='CampusChampion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the campus champion.', max_length=255)),
                ('referral_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='champions', to='campus_champions.championlevel')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('champion_level_name', models.CharField(blank=True, max_length=50)),
                ('champion_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gateway_transaction_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='campus_champions.campuschampion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
