# Generated by Django 6.0.1 on 2026-06-30 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_champions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuschampion',
            name='level',
        ),
        migrations.RemoveField(
            model_name='campuschampion',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='referralusage',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='referralusage',
            name='champion_commission_rate',
        ),
        migrations.RemoveField(
            model_name='referralusage',
            name='champion_level_name',
        ),
        migrations.AddField(
            model_name='campuschampion',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='campuschampion',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='referralusage',
            constraint=models.UniqueConstraint(fields=('champion', 'user'), name='unique_champion_user_referral'),
        ),
        migrations.DeleteModel(
            name='ChampionLevel',
        ),
    ]
