# Generated by Django 6.0.1 on 2026-06-30 09:06

import uuid
from django.db import migrations, models


def populate_uuid_primary_keys(apps, schema_editor):
    table_name = 'campus_champions_referralusage'

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'SELECT "id" FROM "{table_name}" WHERE "id_uuid" IS NULL')
        existing_ids = [row[0] for row in cursor.fetchall()]

        for old_id in existing_ids:
            cursor.execute(
                f'UPDATE "{table_name}" SET "id_uuid" = %s WHERE "id" = %s',
                [uuid.uuid4(), old_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('campus_champions', '0002_remove_campuschampion_level_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "campus_champions_referralusage" ADD COLUMN "id_uuid" uuid',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunPython(populate_uuid_primary_keys, migrations.RunPython.noop),
                migrations.RunSQL(
                    sql='ALTER TABLE "campus_champions_referralusage" ALTER COLUMN "id_uuid" SET NOT NULL',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "campus_champions_referralusage" DROP CONSTRAINT "campus_champions_referralusage_pkey"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "campus_champions_referralusage" DROP COLUMN "id"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "campus_champions_referralusage" RENAME COLUMN "id_uuid" TO "id"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "campus_champions_referralusage" ADD PRIMARY KEY ("id")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='referralusage',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
