# Generated by Django 6.0.1 on 2026-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_champions', '0003_alter_referralusage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuschampion',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10, help_text="Discount percentage (0–100) applied when this champion's code is used."),
        ),
    ]
