# Generated by Django 6.0.1 on 2026-04-25 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0002_alter_notebookfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('custom_prompt', models.TextField(blank=True)),
                ('slide_count', models.IntegerField()),
                ('text_length', models.CharField(choices=[('BRIEF', 'Brief'), ('BALANCED', 'Balanced'), ('DETAILED', 'Detailed')], default='BALANCED', max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField()),
                ('layout', models.CharField(default='content', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('bullets', models.JSONField(default=list)),
                ('speaker_notes', models.TextField(blank=True)),
                ('images', models.JSONField(default=list)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentation.presentation')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
