# Generated by Django 6.0.1 on 2026-05-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationslide',
            name='body_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='quote_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='presentationslide',
            name='layout',
            field=models.CharField(default='bullets', max_length=32),
        ),
    ]
