# Generated by Django 6.0.1 on 2026-08-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_presentationslide_body_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='theme',
            field=models.CharField(choices=[('freshr', 'Freshr'), ('minimal', 'Minimal'), ('dark', 'Dark'), ('academic', 'Academic'), ('serif', 'Serif')], default='freshr', max_length=16),
        ),
    ]
