# Generated by Django 6.0.1 on 2026-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates whether the user account is active. New email-registered users start inactive and must verify their email before this flips to True. Google-registered users are activated immediately on first sign-in.'),
        ),
    ]
