# Generated by Django 6.0.1 on 2026-03-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user account is active. Defaults to False and user needs to verify email on signup before it can be set to True.'),
        ),
    ]
