# Generated by Django 6.0.1 on 2026-07-12 07:24

from django.db import migrations, models

GMAIL_DOMAINS = frozenset({'gmail.com', 'googlemail.com'})


def _normalize_email(email):
    email = email.strip().lower()
    local, sep, domain = email.partition('@')
    if not sep:
        return email
    local = local.split('+', 1)[0]
    if domain in GMAIL_DOMAINS:
        local = local.replace('.', '')
    return f'{local}@{domain}'


def backfill_normalized_email(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all().iterator():
        User.objects.filter(pk=user.pk).update(normalized_email=_normalize_email(user.email))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='normalized_email',
            field=models.EmailField(db_index=True, default='', editable=False, help_text='Canonical form of `email` (lowercased, +tag and Gmail dots stripped), used to detect alias-based duplicate signups against the same inbox.', max_length=254),
        ),
        migrations.RunPython(backfill_normalized_email, migrations.RunPython.noop),
    ]
