# Generated by Django 6.0.1 on 2026-03-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', help_text="URL of the user's profile picture.", max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='tier_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='FREE', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(help_text="The user's first name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(help_text="The user's last name.", max_length=100),
        ),
    ]
