# Generated by Django 6.0.1 on 2026-02-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=1111112345),
            preserve_default=False,
        ),
    ]
