# Generated by Django 6.0.1 on 2026-04-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_refactor_tier_plan_add_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='storage_bytes_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quizzes_generated', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'date')},
            },
        ),
    ]
