# Generated by Django 6.0.1 on 2026-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_storage_bytes_used_dailyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='presentations_generated',
            field=models.IntegerField(default=0),
        ),
    ]
