# Generated by Django 6.0.1 on 2026-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dailyusage_presentations_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyusage',
            name='presentations_generated',
        ),
        migrations.AddField(
            model_name='account',
            name='presentations_generated',
            field=models.IntegerField(default=0),
        ),
    ]
