# Generated by Django 6.0.1 on 2026-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_dailyusage_presentations_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_interval',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('SEMESTER', 'Semester'), ('YEARLY', 'Yearly')], max_length=10, null=True),
        ),
    ]
