# Generated by Django 6.0.1 on 2026-09-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_billing_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='university',
            field=models.CharField(blank=True, default='', help_text="The user's university. Free text: picked from a curated list on the client, or typed in when they choose 'Other'.", max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('YEAR_1', '1st Year'), ('YEAR_2', '2nd Year'), ('YEAR_3', '3rd Year'), ('YEAR_4', '4th Year'), ('MASTERS', 'Masters/Postgrad'), ('GRADUATED', 'Graduated')], default='', help_text="Where the user is in their degree. Blank means they didn't say.", max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
