# Generated by Django 6.0.1 on 2026-09-07 15:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_university_account_year_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCommunitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='When on, onboarding shows the community step and the account page shows a join card.')),
                ('invite_url', models.URLField(blank=True, default='', help_text='The https://chat.whatsapp.com/... group invite link. WARNING: resetting or revoking the invite inside WhatsApp — or the group reaching its participant limit — silently breaks the button with no signal on our side. Re-paste the link after any reset.', max_length=500, validators=[accounts.models.validate_whatsapp_invite_url])),
                ('headline', models.CharField(default='Join the FRESHR student community', max_length=200)),
                ('message', models.TextField(default="Study tips, feature updates and a direct line to the team — plus students from other campuses. It's a WhatsApp group, and you can leave any time.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp community settings',
                'verbose_name_plural': 'WhatsApp community settings',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='whatsapp_community_opt_in_at',
            field=models.DateTimeField(blank=True, help_text="When the user tapped 'Join community' and we opened the WhatsApp invite for them. This records consent and intent ONLY — WhatsApp exposes no way to verify that they actually joined the group, and we will never know if they later leave. Null means they never tapped it.", null=True),
        ),
    ]
