# Generated by Django 6.0.1 on 2026-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_whatsapp_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('YEAR_1', '1st Year'), ('YEAR_2', '2nd Year'), ('YEAR_3', '3rd Year'), ('YEAR_4', '4th Year'), ('YEAR_5', '5th Year'), ('YEAR_6', '6th Year'), ('MASTERS', 'Masters/Postgrad'), ('GRADUATED', 'Graduated')], default='', help_text="Where the user is in their degree. Blank means they didn't say.", max_length=12),
        ),
    ]
