"""
Django settings for freshr project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-w@hqs_0!7r_)6on$(cs(c*5_mbr3)=y9%2p-b5_=8cjm0wda^=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '0.0.0.0,127.0.0.1,localhost,web').split(',')

# Caddy (and nginx-in-frontend) terminate TLS upstream of Django. Without this,
# request.is_secure() returns False and CSRF rejects same-origin POSTs as
# "Origin checking failed - https://... does not match any trusted origins".
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Required for HTTPS admin/CSRF-protected POSTs. Include scheme.
# e.g. "https://staging.freshr.cc,https://freshr.cc"
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # Local prod-parity build (docker-compose.local-prod.yml). Only needed if
    # you point that build straight at Django (VITE_API_BASE_URL=:8000); the
    # default same-origin mode goes through nginx's /api/ proxy and needs no CORS.
    "http://localhost:8090",
    "http://127.0.0.1:8090",
    "https://freshr.cc",        # Production React (port 80)
    "https://www.freshr.cc",        # Production React (www)
    "https://staging.freshr.cc",   # Staging React
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_celery_results',
    "anymail",

    'pgvector',

    # OUR APPS
    'corsheaders',
    'users',
    'accounts',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    "notebooks",
    "rag",
    "chats",
    "presentation",
    "quiz",
    "drf_spectacular",
    "payments",
    "policies",
    "transcription",
    "campus_champions"
]

# Custom User Model
AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.SubscriptionExpiryMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'freshr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freshr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'freshr'),
        'USER': os.getenv('DB_USER', 'freshr'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'freshr'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

MEDIA_ROOT = BASE_DIR / "media"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # ScopedRateThrottle only kicks in for views that set `throttle_scope`, so this
    # is opt-in per view and won't accidentally limit other endpoints.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'verify_email_resend': '5/hour',
        # Audio: rate-limit guardrails (not usage caps). Sized so a power user — a
        # few lectures/day with regenerations — won't notice, but scripted abuse will.
        'audio_transcribe': '30/hour',
        'audio_generate_notes': '60/hour',
        'audio_transcript_update': '120/hour',
    },
}

# Single source of truth for the URL API version (the `vN` in `/api/vN/`).
# This is the API *contract* version, not the release version — bump it only
# when making a breaking change, and run the old version alongside the new one
# so already-installed mobile apps keep working. The release/build number
# (`VERSION` below) is what tracks every update.
API_VERSION = 1

SPECTACULAR_SETTINGS = {
    "TITLE": "Notebook API",
    "DESCRIPTION": "API for notebooks and notebook files",
    "VERSION": "1.0.0",
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": rf"/api/v{API_VERSION}/",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "UPDATE_LAST_LOGIN": True,
}

# Tier Limits
FRESHR_TIER_LIMITS = {
    "FREE": {
        "max_notebooks": 3,
        "max_files_per_notebook": 2,
        "max_size_per_file_mega_bytes": 10,
        "max_quizzes_per_day": 5,
        "max_presentations_total": 2,
        "storage_mega_bytes": 60,
        "audio_feature_enabled": False,
    },
    "PAID": {
        "max_notebooks": "unlimited",
        "max_files_per_notebook": "unlimited",
        "max_size_per_file_mega_bytes": 50,
        "max_quizzes_per_day": "unlimited",
        "max_presentations_total": "unlimited",
        "storage_mega_bytes": 2000,
        "audio_feature_enabled": True,
    },
}


# Cache backend: Redis. Used by DRF's ScopedRateThrottle so throttle counters
# are shared across gunicorn workers (LocMemCache would make each worker have
# its own counter, multiplying the effective limit by the worker count).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/0"),
    }
}

# Celery
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_RESULT_EXTENDED = True
CELERY_TIMEZONE = "Asia/Dhaka"

# Recycle prefork workers periodically to guard against slow memory growth over time.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50

CELERY_BEAT_SCHEDULE = {"expire-subscriptions": {"task": "accounts.tasks.expire_subscriptions", "schedule": crontab(minute=0)}}

# Email Configuration — Resend via django-anymail. Sender addresses live on the
# verified no-reply.freshr.cc subdomain; per-purpose mailboxes (support@, security@)
# let recipients and inbox providers distinguish transactional categories.
EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("RESEND_API_KEY"),
}
DEFAULT_FROM_EMAIL = 'REFRSH <no-reply@no-reply.freshr.cc>'
PASSWORD_RESET_FROM_EMAIL = 'REFRSH Support <support@no-reply.freshr.cc>'
VERIFICATION_FROM_EMAIL = 'REFRSH <security@no-reply.freshr.cc>'
FRONTEND_URL = os.getenv("FRONTEND_URL", 'http://localhost:3000')

# Google OAuth2.0
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET')

# ZiniPay
ZINIPAY_API_KEY = os.getenv('ZINIPAY_API_KEY', '')
ZINIPAY_MONTHLY_PRICE = os.getenv('ZINIPAY_MONTHLY_PRICE', '350')
ZINIPAY_YEARLY_PRICE = os.getenv('ZINIPAY_YEARLY_PRICE', '1200')

USE_MOCK_PAYMENT_GATEWAY = os.getenv('USE_MOCK_PAYMENT_GATEWAY', '').lower() in ('true', '1', 'yes')

# Public URL of this backend (used for webhook registration)
BACKEND_URL = os.getenv('BACKEND_URL', 'http://localhost:8000')

# JSON logging so Dozzle can recognize levels and color them. Tracebacks are
# emitted as an array of lines under `traceback` (see DozzleJsonFormatter) so
# they stay readable in Dozzle instead of becoming an escaped single-line blob.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'freshr.logging_formatters.DozzleJsonFormatter',
            'format': '%(levelname)s %(name)s %(message)s %(asctime)s',
            'rename_fields': {'levelname': 'level', 'asctime': 'time', 'name': 'logger'},
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'celery': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}