# Generated by Django 6.0.1 on 2026-08-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='generation_status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=15),
        ),
    ]
