# Generated by Django 6.0.1 on 2026-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
    ]
