# Generated by Django 6.0.1 on 2026-06-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
