# Generated by Django 6.0.1 on 2026-08-13 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_dailyusage_presentations_generated_and_more'),
        ('payments', '0003_payment_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFallbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='When on, the billing page hides checkout and shows the contact-sales form instead.')),
                ('headline', models.CharField(default='Online payment is temporarily unavailable', max_length=200)),
                ('message', models.TextField(default="We're sorry for the inconvenience — our payment gateway is down while we finish setting up bKash. You can still upgrade: leave your details below and someone from our team will contact you to get your paid access sorted.")),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Sales WhatsApp number in international format, digits only (e.g. 8801712345678).', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment fallback settings',
                'verbose_name_plural': 'Payment fallback settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentAssistanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('billing_interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('referral_code', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=15)),
                ('handled_by', models.CharField(blank=True, default='', max_length=254)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
