# Generated by Django 6.0.1 on 2026-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentfallbacksettings_paymentassistancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='billing_interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMESTER', 'Semester'), ('YEARLY', 'Yearly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentassistancerequest',
            name='billing_interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMESTER', 'Semester'), ('YEARLY', 'Yearly')], max_length=10),
        ),
    ]
