# Generated by Django 6.0.2 on 2026-02-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookfile',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notebookfile',
            name='name',
            field=models.CharField(default='Untitled', max_length=20),
        ),
    ]
