# Generated by Django 6.0.1 on 2026-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notebook_archived_at_notebook_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
