# Generated by Django 6.0.1 on 2026-07-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_alter_notebook_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookfile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
