# Generated by Django 6.0.1 on 2026-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_notebook_updated_at_alter_notebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
