# Generated by Django 6.0.1 on 2026-06-13 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0004_alter_notebook_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('transcript_text', models.TextField(blank=True)),
                ('notes_text', models.TextField(blank=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcription_error', models.TextField(blank=True)),
                ('notes_status', models.CharField(choices=[('not_started', 'Not started'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('notes_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_transcripts', to='notebooks.notebook')),
                ('notes_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_transcript', to='notebooks.notebookfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
